# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-ranger}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["brianthecoder"]
  s.date = %q{2010-06-02}
  s.default_executable = %q{resque-ranger}
  s.description = %q{Super fast evented daemon to process resque jobs, some built in job metrics too, just cause your app might not be on 1.9.1, your bot might be able to}
  s.email = %q{wbsmith83@gmail.com}
  s.executables = ["resque-ranger"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/resque-ranger",
     "lib/raemon/runner.rb",
     "lib/resque-ranger.rb",
     "lib/resque/ranger.rb",
     "lib/resque/runner.rb",
     "resque-ranger.gemspec",
     "test/helper.rb",
     "test/test_resque-ranger.rb"
  ]
  s.homepage = %q{http://github.com/BrianTheCoder/resque-ranger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Super fast evented daemon to process resque jobs, some built in job metrics too}
  s.test_files = [
    "test/helper.rb",
     "test/test_resque-ranger.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, ["= 1.0.4"])
      s.add_runtime_dependency(%q<resque>, ["= 1.8.0"])
      s.add_runtime_dependency(%q<eventmachine>, ["= 0.12.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<redis>, ["= 1.0.4"])
      s.add_dependency(%q<resque>, ["= 1.8.0"])
      s.add_dependency(%q<eventmachine>, ["= 0.12.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<redis>, ["= 1.0.4"])
    s.add_dependency(%q<resque>, ["= 1.8.0"])
    s.add_dependency(%q<eventmachine>, ["= 0.12.0"])
  end
end

